version: "3.9"

services:
  agent-latest:
    image: powerpool/power-agent-node:latest
    restart: always
    volumes:
      - ./config:/usr/app/config
      - ./keys:/usr/app/keys
    ports:
      - "${NODE_API_PORT:-8099}:${NODE_API_PORT:-8099}"
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${NODE_API_PORT:-8099}
    profiles: [latest]

  agent-dev:
    image: powerpool/power-agent-node:dev
    restart: always
    volumes:
      - ./config:/usr/app/config
      - ./keys:/usr/app/keys
    ports:
      - "${NODE_API_PORT:-8099}:${NODE_API_PORT:-8099}"
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${NODE_API_PORT:-8099}
      OFFCHAIN_SERVICE_ENDPOINT: http://offchain-service:${OFFCHAIN_API_PORT:-3423}
    profiles: [dev]

  offchain-service:
    image: powerpool/power-agent-offchain-service:latest
    restart: always
    volumes:
      - ./scriptsFetched:/scriptsFetched
      - ./scriptToExecute:/scriptToExecute
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${OFFCHAIN_API_PORT:-3423}:${OFFCHAIN_API_PORT:-3423}"
    environment:
      AGENT_API_HOST: http://localhost:${NODE_API_PORT:-8099}
      DOCKER_MODE: 1
    profiles: [latest, dev]

  temp-executor:
    image: node:18-alpine
