version: "3.9"
services:
  bot:
    image: polipaul/agent-v2-bot:latest
    restart: always
    volumes:
      - ./config:/usr/app/config
      - ./keys:/usr/app/keys
  agent:
    image: powerpool-finance/powerpool-agent-v2-node:latest
    restart: always
    volumes:
      - ./config:/usr/app/config
      - ./keys:/usr/app/keys


